# Project: 循环求最小公倍数2.0
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o
LINKOBJ  = main.o
LIBS     = -L"D:/Document ontology/Dev/Dev-Cpp/TDM-GCC-64/lib" -L"D:/Document ontology/Dev/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/Document ontology/Dev/Dev-Cpp/TDM-GCC-64/include" -I"D:/Document ontology/Dev/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Document ontology/Dev/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"D:/Document ontology/Dev/Dev-Cpp/TDM-GCC-64/include" -I"D:/Document ontology/Dev/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Document ontology/Dev/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"D:/Document ontology/Dev/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = 循环求最小公倍数2.0.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = D:\Document ontology\Dev\Dev-Cpp\DevCpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)
